// generated by "sampctl package init"
#include <a_samp>
#include <dev-commands>

main() 
{
	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	return 0;
}